FROM nginx:latest
RUN mkdir /etc/nginx/ssl
# Use mount volume
#RUN chown nginx:nginx /var/www/html/*
#RUN chmod -R +rx /var/www/html/sociolog.local/public/assets
#RUN chmod -R +rx /var/www/html/sociolog.local/public/images